// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roechfblafwkzgvwyaqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZWNoZmJsYWZ3a3pndnd5YXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTk1ODEsImV4cCI6MjA2MzkzNTU4MX0.p0VbR4IuZtukKld0MrwrdEbwyzuOZuznseuioKOUWZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);